language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
 - composer install --dev --prefer-source

script:
 - phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

notifications:
  email: false
